version: '2'
services:
  bme680:
    image: ghcr.io/thinkier/bme688-http-api
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: host
    devices:
      - /dev/i2c-1:/dev/i2c-1
